name: lipl_ble
description: Library to scan for BLE display service and writing to characteristic

publish_to: 'none'

version: 1.2.0

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.0.3
  equatable: ^2.0.5
  logging: ^1.1.1
  bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  bloc_test: ^9.1.1
