name: lipl_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.0.2
  cupertino_icons: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  lipl_repo: 
    git:
      url: git://paulmin.nl/dart/lipl-repo.git
      ref: v0.7
  logging: ^1.0.2
  parts: 
    git:
      url: git://paulmin.nl/dart/parts.git
      ref: v0.2
  lipl_preferences_bloc:
    git:
      url: git://paulmin.nl/dart/lipl-preferences-bloc.git
      ref: v0.1

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ca/lets-encrypt-r3.pem

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff

