name: lipl_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  bs58: ^1.0.2
  bloc: ^8.0.2
  cupertino_icons: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  json_annotation: ^4.4.0
  lipl_repo: 
    git:
      url: git://paulmin.nl/dart/lipl-repo.git
      ref: v0.3
#  stream_transform: ^2.0.0
#  uuid: ^3.0.5

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
