name: lipl_bloc
description: A new Flutter project.
publish_to: 'none'
version: 1.1.0

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^8.0.2
  cupertino_icons: ^1.0.1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.4.0
  lipl_ble:
    git:
      url: git://paulmin.nl/dart/lipl-ble.git
      ref: v0.4
  lipl_rest_bloc: 
    git:
      url: git://paulmin.nl/dart/lipl-rest-bloc.git
      ref: v0.5
  logging: ^1.0.2
  parts: 
    git:
      url: git://paulmin.nl/dart/parts.git
      ref: v0.2
  preferences_bloc:
    git:
      url: git://paulmin.nl/dart/preferences-bloc.git
      ref: v0.4
  shared_preferences: ^2.0.13
  permission_handler: ^9.2.0

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/ca/lets-encrypt-r3.pem

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/icon.png'
  remove_alpha_ios: true
  adaptive_icon_background: #ffffff

