name: preferences_bloc
description: Library for handling preferences changes and storing
version: 1.2.0

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=3.7.12 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  equatable: ^2.0.5

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
