name: lipl_encrypt
description: A starting point for Dart libraries or applications.
version: 1.2.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  encrypt: ^5.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
